import { Inter } from "next/font/google";
import "./globals.css";
import HEADER from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ProyectoNextRoca",
  description: "Generated by create next app",
};

<meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-stone-900 ${inter.className}`}>
        <HEADER />
        {children}
      </body>
    </html>
  );
}
